### ISSUE TITLE
Make it easy to change COYOTE_PATTERN.

### ISSUE THREAD

**Issue by ghost** [Sakura0721/osc-toys#2]
Currently COYOTE_PATTERN cannot be changed without editing settings.py and rebooting.
It would be ideal to be able to change it from within VRChat via OSC
Or make it possible to change from the GUI. (if GUI is added)

**Comment by Sakura0721** [comment]
True.
Currently I am working on a new GUI (or webUI exactly), which will support runtime switch of pattern.
Because for now this project is only maintained by me and I have other works to do, the progress might be slow. Hopefully, it will be finished within a week.

Change pattern with VRC quick action menu (via OSC) is also a good idea, will consider to add that feature later.

**Comment by Sakura0721** [comment]
WebUI features were added after #3 merged.
You can try it out at [release page](https://github.com/Sakura0721/osc-toys/releases/tag/v0.0.1)
